CREATE TABLE `motor_proposal_form`.`motor_vehicle_inspection_form` 
(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name_of_proposer` VARCHAR(100) NOT NULL,
    `address` VARCHAR(100) NOT NULL,
    `registration_number` VARCHAR(100) NOT NULL,
    `vehicle_make` VARCHAR(100) NOT NULL,
    `vehicle_colour` VARCHAR(100) NOT NULL,
    `chassis_number` VARCHAR(100) NOT NULL,
    `engine_number` VARCHAR(100) NOT NULL,
    `body_type` VARCHAR(100) NOT NULL,
    `manufacture_year` VARCHAR(100) NOT NULL,
    `speedometer_reading` VARCHAR(100) NOT NULL,
    `estimate_value` VARCHAR(100) NOT NULL,
    `accessory_value` VARCHAR(100) NOT NULL,
    `anti_theft` VARCHAR(100) NOT NULL,
    `previous_damage` VARCHAR(100) NOT NULL,
    `inspection_time` VARCHAR(100) NOT NULL,
    `remarks` VARCHAR(100) NOT NULL,
    `inspector_name` VARCHAR(100) NOT NULL,
    `inspector_sign` VARCHAR(100) NOT NULL,
    `insured_name` VARCHAR(100) NOT NULL,
    `insured_sign` VARCHAR(100) NOT NULL,
    `date` VARCHAR(100) NOT NULL,
    `inspection_location` VARCHAR(100) NOT NULL,
    `vehicle_front` VARCHAR(100) NOT NULL,
    `vehicle_back` VARCHAR(100) NOT NULL,
    `vehicle_left` VARCHAR(100) NOT NULL,
    `vehicle_right` VARCHAR(100) NOT NULL,
PRIMARY KEY (`id`) 
);