CREATE TABLE `motor_proposal_form`.`motor_proposal_form_individual` 
(
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name_of_proposal` VARCHAR(100) NOT NULL,
    `address` VARCHAR(100) NOT NULL,
    `town` VARCHAR(100) NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NOT NULL,
    `country` VARCHAR(100) NOT NULL,
    `business_phone` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `fax` VARCHAR(100) NOT NULL,
    `url` VARCHAR(100) NOT NULL,
    `tin` VARCHAR(100) NOT NULL,
    `bvn` VARCHAR(100) NOT NULL,
    `risk_address` VARCHAR(100) NOT NULL,
    `cover_type` VARCHAR(100) NOT NULL,
    `cover_period` VARCHAR(100) NOT NULL,
    `property_value` VARCHAR(100) NOT NULL,
    `beneficiary` VARCHAR(100) NOT NULL,
    `other_policy` VARCHAR(100) NOT NULL,
    `means_of _id` VARCHAR(100) NOT NULL,
    `proof_of_address` VARCHAR(100) NOT NULL,
    `vehicle_type` VARCHAR(100) NOT NULL,
    `cover_required` VARCHAR(100) NOT NULL,
    `period_from` VARCHAR(100) NOT NULL,
    `period_to` VARCHAR(100) NOT NULL,
    `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `sign_of_proposal` VARCHAR(100) NOT NULL,
    `name_of_proposal` VARCHAR(100) NOT NULL,
PRIMARY KEY (`id`) 
);